### ISSUE TITLE
Cannot open Excel or Presentation files 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms#46]
This issue is raised in https://forum.groupdocs.com/t/cant-open-file-by-dynamic-post-filename-some-type/9358

Hi,
When I try to open a PDF or Image file by specifying file name [here](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms/blob/master/src/Products/Annotation/Controllers/AnnotationApiController.cs#L133). It works well. As I try to open an Excel or Presentation file same way, I get exception and document is not displayed or rendered. 
It says :
_Cannot open presentation_ or _Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index_
Please have a look at the attached screenshots.
[screenshots.zip](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms/files/6057432/screenshots.zip)

**Comment by qzsaikz1** [comment]
pls check case annotation for image and case open every type file thanks so much

![image](https://user-images.githubusercontent.com/33310775/109489473-81ca7680-7ab9-11eb-9e6e-3acf70b9a6fd.png)

**Comment by bobkovalex** [comment]
@qzsaikz1 @atirtahirgroupdocs 

I apologise for not replying sooner.
We've released updated version with following changes:

**Fixes**
1. Powerpoint documents -> Fixed
2. ODT -> Fixed
5. Pictures -> Fixed
6. PDF -> Fixed

**Known Issues**
1. Excel document can be opened but won't annotate;
2. ODS & ODP can be opened but won't annotate;
3. VSD can be opened but returns size 0;
4. Can't read AutoCAD documents;
7. HTML Can be opened but returns size 0.

We are working on remaining issues and will release fixes ASAP.

Best Regards

**Comment by qzsaikz1** [comment]
Thanks so much , I hope your team will fixed all issue soon 
I'm try too.

**Comment by qzsaikz1** [comment]
> @qzsaikz1 @atirtahirgroupdocs
> 
> I apologise for not replying sooner.
> We've released updated version with following changes:
> 
> **Fixes**
> 
> 1. Powerpoint documents -> Fixed
> 2. ODT -> Fixed ** [ Test annotation and save document not load annotation ]
> 3. Pictures -> Fixed
> 4. PDF -> Fixed
> 
> **Known Issues**
> 
> 1. Excel document can be opened but won't annotate;
> 2. ODS & ODP can be opened but won't annotate;
> 3. VSD can be opened but returns size 0;
> 4. Can't read AutoCAD documents;
> 5. HTML Can be opened but returns size 0.
> 
> We are working on remaining issues and will release fixes ASAP.
> 
> Best Regards

**Comment by bobkovalex** [comment]
The issue has been moved to:
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET/issues/97
