### ISSUE TITLE
Could not load annotation config

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms#49]
https://forum.groupdocs.com/t/how-fix-error-could-not-load-annotation-config/9452

Hi,
Please have a look at the attached image.
![Untitled](https://user-images.githubusercontent.com/15940608/111822357-838f9900-8905-11eb-9492-1cbe73e061f1.png)
Application is deployed on server but giving this issue.
Please take a look.
Thanks

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, for the current implementation of GroupDocs.Annotation sample app, we could suggest to change default URL presented on the line https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms/blob/master/src/client/apps/annotation/src/app/app.module.ts#L10
to the new one for which the back-end part of the application is available, then re-build the project to apply this change.

**Comment by qzsaikz1** [comment]
Thanks for the answer. But tried and the result is not different. 
![image](https://user-images.githubusercontent.com/33310775/112608882-73b80d80-8e4d-11eb-9a23-98486786eded.png)

**Comment by kegor** [comment]
Hi @qzsaikz1,
We've prepared a short step-by-step guide on how-to run our sample on custom/own IP (non localhost).
Please see if this helps: https://conholdate.app/products/viewer/view/59mhVoboa6I5O4DL3/using-custom-host-url-step-by-step-guide.docx?preview=true.pdf
Also, please verify that after finishing all steps there is no `localhost` urls present in any of the js files.

Thanks.

**Comment by qzsaikz1** [comment]
This case can fixed, Thx so much =)
