### ISSUE TITLE
Is it possible to fix Polyline to Freehand draw same Total Annotation?

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms#53]
This issue is raised in https://forum.groupdocs.com/t/we-can-fix-polyline-to-freehand-draw-same-total-annotation/9619
Hi,
Please have a look at the following screenshot.
![image](https://user-images.githubusercontent.com/15940608/116377910-138d0080-a82b-11eb-9d61-a3f55b385746.png)
When we use the polyline tool, we cannot write continuous memos because each time the pen is raised, the tool must be selected again. Can we change polyline to freehand?

Thanks

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

We’ve implemented requested feature (toggle buttons for annotations).
Just rebuild the project and make sure that latest @groupdocs.examples.angular/annotation version is fetched from npm.
Toggle buttons support is available starting from 0.8.54.

![127635259-c82897e3-5ef9-4e89-990d-c53c920db18d](https://user-images.githubusercontent.com/2103709/127646783-f8de63f7-6948-42ab-b3f9-8cb1ead98afa.gif)


Best Regards,
Alex
