### ISSUE TITLE
PDF scanned file has low resolution when opened in web app

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms#55]
This issue is raised in https://forum.groupdocs.com/t/document-has-low-resolution-pdf-scan-file/9658

Hi,
Please find the problematic file attached. 
[pdf_file_scan_test.pdf](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms/files/6495209/pdf_file_scan_test.pdf).
If you open this PDF in any PDF viewer the result or the appearance is different as compare to the appearance we have in the web application. 
Take a look at the following image. 
![screenshot](https://user-images.githubusercontent.com/15940608/118523192-579e6180-b756-11eb-8d13-7114c096dbfc.PNG)
Could you please see why the resolution is effected?

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

Thanks for reporting, I've been able to reproduce the issue.
We will look into it.

Regards

**Comment by qzsaikz1** [comment]
pls follow this case.

**Comment by bobkovalex** [comment]
Issue has been resolved on 31th of May
https://forum.groupdocs.com/t/document-has-low-resolution-pdf-scan-file/9658/7

Repository has moved to:
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET/tree/master/Demos/WebForms
